apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec: # Moved to the left to align with metadata
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec: # Moved to the left to align with metadata
  containers:
    - name: httpd-container
      image: httpd:latest
      ports:
        - containerPort: 80