apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec: # Moved to the left to align with metadata
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80